package e93.assembler;

import javax.annotation.Generated;

/**
 * @author markford
 */
public enum OpCode {
    ALU(1),
    ADDI(2),
    ORI(3),
    SW(4),
    LW(5),
    J(6);

    private final int value;

    OpCode(int value) {
        this.value = value;
    }

    @Generated("generated by IDE")
    public int getValue() {
        return value;
    }

    public static OpCode fromEncoded(int value) {
        for(OpCode oc : values()) {
           if (oc.getValue() == value) {
               return oc;
           }
        }
        throw new IllegalArgumentException("unknown opcode:" + value);
    }
}
