package e93.assembler;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.function.Supplier;

/**
 * @author markford
 */
public enum OpCode {
    ALU(1), ADDI(2);

    private final int value;

    OpCode(int value) {
        this.value = value;
    }

    @Generated("generated by IDE")
    public int getValue() {
        return value;
    }

    public static OpCode fromEncoded(int value) {
        for(OpCode oc : values()) {
           if (oc.getValue() == value) {
               return oc;
           }
        }
        throw new IllegalArgumentException("unknown opcode:" + value);
    }
}
